-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: localhost
-- Generation Time: Nov 22, 2024 at 01:21 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `travelapps`
--

-- --------------------------------------------------------

--
-- Table structure for table `paket`
--

CREATE TABLE `paket` (
  `id` int(11) NOT NULL,
  `nama_paket` varchar(100) NOT NULL,
  `harga` decimal(10,2) NOT NULL,
  `deskripsi` text DEFAULT NULL,
  `fasilitas` text DEFAULT NULL,
  `foto` varchar(255) DEFAULT NULL,
  `rincian` text DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `paket`
--

INSERT INTO `paket` (`id`, `nama_paket`, `harga`, `deskripsi`, `fasilitas`, `foto`, `rincian`) VALUES
(20, 'Fun Trekking Ciwangun Indah', 350000.00, 'Trekking santai di Bandung! mau liburan ke alam tapi bosan sama yang itu-itu aja? tempat ini masih jarang diketahui dan alami. \r\n\r\nkita akan menyusuri sungai, menyebrang dengan jembatan kayu atau bambu, dan naik turun jalan berbatu. pastikan kamu memakai sepatu yang nyaman ya. jalan menuju curug berada di lembah dengan tebing di kiri dan kanan. suasananya sejuk dan alami banget. hati-hati karena jalannya licin dan berlumut.\r\n\r\nkita akan menginjungi 2 air terjun, curug putri, dan curug tilu. sepanjangan perjalanan mata akan dimanjakan dengan kebun teh, hutan pinus dan udara segar. tak hanya itu, kita juga akan mengunjungi goa tokek, objek wisata goa yang dulunya memiliki banyak tokek namun saat ini langka karena diburu untuk obat.\r\n\r\nDi curug tilu, kalian bisa berendam di aliran sungai.\r\n\r\nsiapkan pakaian ganti, alas kaki sepatu dan sendal gunung yang nyaman, trekking pole (bila perlu), jaket dan jas hujan. jangan lupa bawa minum dan snack untuk menjaga stamina selama trekking.', 'Paket tour termasuk :\r\n\r\n- Transportasi dengan bus/hiace white horse\r\ndriver, BBM, Tol & Parkir\r\n\r\n- tiket masuk ciwangun indah camp\r\n\r\n- kunjungan curug putri\r\n\r\n- kunjungan curug tilu\r\n\r\n- kunjungan hutan pinus\r\n\r\n- kunjungan goa tokek\r\n\r\n- kunjungan perkebunan teh\r\n\r\n- Guide lokal selama trekking\r\n\r\n- Tour Leader\r\n\r\nPaket Tour tidak termasuk :\r\n\r\n- penambahan destinasi diluar program\r\n\r\n- pengeluaran keperluan pribadi selama perjalanan\r\n\r\n- tipping tour leader dan driver', '67208ac75b7ae-ciwangun.png', '-Berkumpul di Meeting Point (06:30)\r\n\r\nExit Tol Pasteur (Long Day Trip)\r\nexit Tol Buah Batu (Long Trip)\r\nExit Tol Soraja (Long Trip)\r\n\r\n- Ciwangun Indah Camp (09:30)\r\n\r\nPerkiraan tiba di base camp CIC dan persiapan untuk melakukan trekking\r\n\r\nStart Trekking (10:00)\r\n\r\nStart Trekking dengan Rute melewati beberapa tempat :\r\n- curug Putri\r\n- curug Golosor\r\n- curug tilu\r\n- hutan pinus \r\n- goa tokek\r\n- perkebunan teh\r\n\r\nPerjalanan Menuju Pusat Oleh-oleh (15:00)\r\n\r\ndi tempat oleh-oleh ini banyak menjual makanan ringan yang sangat cocok dijadikan untuk oleh-oleh bagi orang terdekat.\r\n\r\nPerjalanan kembali ke meeting point (16:00)\r\n\r\nperjalanan kembali ke meeting point dan trip selesai.'),
(21, 'Stone Garden', 250000.00, 'Tau gak kalau ada taman batu yang diduga dulunya merupakan lautan?  ternyata itu loh sejarah dari stone garden di bandung. di trip ini kita menikmati pemandangan kota bandung di antara bukit batuan ini. kemudian, kita akan mengunjungi goa pawon di mana terdapat fosil kerangka 7 manusia purba yang berasal dari 5.000 - 12.000 tahun silam. penasaran? join tripnya minggu ini!', 'Paket tour termasuk :\r\n\r\n- Transportasi PP bus white horse\r\n\r\n- Tour Leader\r\n\r\n- Tiket wisata stone garden \r\n\r\n- Tiket wisata goa pawon\r\n\r\n- free air kelapa 1x\r\n\r\nPaket Tour tidak termasuk :\r\n\r\n- Makan\r\n- tip kru sukarela \r\n\r\n*note \r\nminimal keberangkatan 10 orang', '67208d9619350-stone_garden.jpg', 'Berkumpul di Meeting Point (07:00)\r\n- Exit Tol Pasteur (Long Day Trip)\r\n- Exit Tol Buah Batu (Long Trip)\r\n- Exit Tol Soraja (Long Trip)\r\n\r\n- Stone Garden (09:30)\r\n\r\ntiba di stone garden & explore stone garden\r\n\r\n- Goa Pawon (12:15)\r\n\r\nTiba di goa Pawon & Explore Goa pawon\r\n\r\n- Perjalanan Menuju Pusat Oleh-oleh (15:00)\r\n\r\nDi Tempat oleh-oleh ini banyak menjual makanan ringan yang sangat cocok dijadikan untuk oleh-oleh bagi orang terdekat\r\n\r\n- Perjalanan kembali ke meeting point (19:00)\r\n\r\nperjalanan kembali menuju meeting point, dan sampai ketemu di trip berikut nya'),
(22, 'Tangkuban Perahu', 275000.00, 'Explore tempat wisata legendaris di bandung, tangkuban perahu! \r\n\r\nTangkuban perahu merupakan gunung di jawa barat dengan ketinggian 2.084 meter dan terkenal dalam legenda sang kuriang. \r\n\r\nsetelah dari tangkuban perahu kita akan mengunjungi tempat wisata baru,  Asstro Highland Ciater.\r\n\r\nDi sini kamu dapat makan siang sambil menikmati makan siang sambil melihat pemandangan kebun teh dan kamu juga bisa berkuda.', 'Paket tour termasuk :\r\n\r\n- Transportasi PP bus white horse\r\n\r\n- Tiket masuk tangkuban perahu \r\n\r\n- Tiket Shuttle tangkuban perahu \r\n\r\n- Tiket masuk asstro highland\r\n\r\n- Tour leader\r\n\r\n- Tol & parkir \r\n\r\nPaket Tour tidak termasuk :\r\n\r\n- Makan\r\n- Penambahan atraksi wisata diluar program\r\n\r\n- Keperluan pribadi selama perjalanan \r\n\r\n- Tipping guide dan driver \r\n\r\n*Notes \r\nminimal keberangkatan 10 orang', '6720eee0dcff1-tangkuban_perahu.jpg', 'Berkumpul di Meeting Point (07:30)\r\n\r\n- Exit Tol Pasteur (Long Day Trip)\r\n- Exit Tol Buah Batu (Long Trip)\r\n- Exit Tol Soraja (Long Trip)\r\n\r\n- Tangkuban Perahu (10:00)\r\n\r\nPerkiraan tiba di tangkuban perahu & explore tangkuban perahu\r\n \r\n- Asstro Highland (13:00)\r\n\r\nTiba Setibanya di Asstro Highland kita akan explore Asstro Highland Ciater. Kamu dapat makan siang dengan pemandangan kebun teh di sini. \r\n\r\n- Perjalanan Menuju Pusat Oleh-oleh (15:00)\r\n\r\ndi Tempat oleh-oleh ini banyak menjual makanan ringan yang sangat cocok dijadikan untuk oleh-oleh bagi orang terdekat\r\n\r\n- Perjalanan kembali ke meeting point (17:00)\r\n\r\nPerjalanan kembali menuju meeting point, dan sampai ketemu di trip berikut nya'),
(23, 'Sunrise Ranca Upas', 325000.00, 'Mau menikmati sunrise tanpa camping? di trip ini kita akan berangkat malam, tiba subuh. jadi kamu bisa istirahat di bus dan tiba di ranca upas sekitar pukul 3 - 4 pagi.\r\n\r\nSetibanya di sini kamu bisa istirahat di bus, atau menunggu dan sarapan di warung. tersedia api unggun, toilet, kamar mandi dan mushola juga di sini.\r\n\r\nsetelah melihat sunrise di padang rumput, kamu dapat mengeskplor penangkaran rusa, kolam renang air panas, dan area camping. untuk memberi makan rusa cukup membayar sekitar rp 10.000,- untuk 1 ikat kangkung atau wortel.\r\n\r\nsetelah dari ranca upas, kita akan mengenjungi pinisi resto, di area ini kamu dapat makan siang di restoran berbentuk kapal yang terdampar di sebelah situ patenggang. kamu dapat menikmati pemandangan danau dari dek kapal dan berfoto di kebun teh mini yang ada di sekitar danau. di pinisi resto juga terdapat permainan golesat dan kapal untuk berkeliling danau.', 'Paket tour termasuk :\r\n\r\n- Transport PP bus white horse\r\n- Tour Leader\r\n- Tiket wisata\r\n\r\nPaket Tour tidak termasuk :\r\n\r\n- Makan\r\n- Tip kru sukarela\r\n\r\n*note\r\nminimal keberangkatan 10 orang', '6720f05f8dd84-sunrise_ranca_upas.jpg', '- Ranca Upas (04:00)\r\n\r\nTiba di ranca upas kita akan hunting sunrise di ranca upas & explore pengkarangan rusa \r\n\r\n- Pinisi resto (pinisi clamping) (08:30)\r\n\r\nPerkiraan tiba di pinisi resto dan explore pinisi resto, disini kalian dapat bermain golesat dengan biaya tambahan rp 50.000/orang untuk 1x permainan, kemudian kalian dapat menaiki perahu untuk mengelilingi danau situ patenggang dengan tambahan biaya rp 30.000/orang untuk 1x putaran\r\n\r\n\r\n- Tempat Oleh-oleh “sari intan” (14:00)\r\n\r\ndi tempat oleh-oleh ini banyak menjual makanan ringan yang sangat cocok dijadikan untuk oleh-oleh orang terdekat.\r\n\r\n- Perjalanan kembali ke meeting point (15:00)\r\n\r\nperjalanan kembali ke meeting point & sampai jumpa di trip selanjutnya.'),
(24, 'Pangalengan Adventure', 350000.00, 'Pemandangan seindah ini gak boleh kamu lewatkan! buat kamu pengejar sunrise, wajib banget cobain lihat sunrise di pangalengan\r\n\r\nmatahari terbit menyinari kebun teh dan jalan berliku. setelah menikmati sunrise sambil sarapan dan berfoto di beragam spot, kamu akan mengunjungi kebun teh wayang windu. dari situ kamu dapat memilih untuk pergi ke rumah ibu yang menjadi lokasi syuting film rumah pengabdi setan atau ke penangkaran rusa disebelahnya.', 'Paket tour termasuk :\r\n\r\n- Transport PP bus white horse\r\n\r\n- Tour Leader\r\n\r\n- Tiket wisata\r\n\r\nPaket Tour tidak termasuk :\r\n\r\n- Tiket masuk rumah pengabdi setan Rp. 10.000,-/orang \r\n\r\n- Harga tiket menuju penangkaran rusa Rp. 10.000,-/orang\r\n\r\n- Makan\r\n\r\n- Tip kru sukarela\r\nflying fox di wayang windu Rp.50.000,-/orang\r\n\r\nATV di wayang windu sekitar Rp.75.000,-/orang', '6720f1e2b4afe-pangalengan.jpg', '- Sunrise Point cukul pangalengan (04:00)\r\n\r\nPerkiraan tiba di sunrise point cukul & melihat sunrise disini. serta dapat sarapan pagi dengan menikmati pemandangan.\r\n\r\n- Wayang windu panenjoan (08:30)\r\n\r\nPerkiraan tiba di wayang windu panenjoan & menglilingi kawasan ini. disini terdapat tempat untuk sewa aTV. \r\n\r\n\r\n- Tempat lokasi syutng film rumah pengabdi setan (11:00)\r\n\r\ntiba dan mengelilingi tempat lokasi ini, jika tidak ingin ke rumah pengabdi setan, dapat berwisata ke penangkaran rusa yang terletak disebelahnya. \r\n\r\n- Tempat oleh-oleh “KPBS Pangalengan” (13:00)\r\n\r\nTiba di tempat oleh-oleh, di tempat ini banyak menjual makanan & minuman ringan yang sangat cocok untuk dijadikan oleh-oleh bagi orang terdekat. \r\n\r\n- Rumah makan ibu eka (14:00)\r\n\r\nTiba di rumah makan ibu eka untuk makan siang (biaya pribadi)\r\n\r\n- perjalanan kembali menuju meeting point\r\n(16:00)\r\n\r\nMulai untuk perjalanan kembali dan sampai jumpa di perjalanan berikutnya.'),
(25, 'Fun Trekking Kawah Ratu', 350000.00, 'Mau olahraga sekaligus melihat pemandangan di tempat yang sepi? trekking kawah ratu pas banget buat kamu yang memiliki stamina FIT karena medannya yang menantang.\r\n\r\ndurasi trekking kurang lebih sekitar 6 jam pP, tapi gak perlu khawatir karena pasti ada waktu untuk istirahat dan tidak akan ditinggal. kita akan menggunakan jalur curug seribu, melewati hutan dan lumpur. tiba di kawah ratu kamu dapat merendam kaki dan berfoto di sungai cikuwulung yang berwarna biru muda. \r\n\r\nsetelah dari kawah ratu kita akan naik mobil menuju curug ngumpet, lelahnya langsung hilang setelah main air atau berenang di air terjun. terdapat warung sederhana untuk makan siang (biaya pribadi).', 'Paket tour termasuk :\r\n\r\n- Transport PP bus white horse\r\n- Tour Leader\r\n- Tiket wisata\r\n\r\nPaket Tour tidak termasuk :\r\n\r\n- Makan\r\n- Tip kru sukarela\r\n\r\n*Note\r\n\r\nMinimal keberangkatan 5 orang', '6720f56a6a5fc-kawah_ratu.jpg', '- Tiba di basecamp kawah ratu (09:00)\r\n\r\nPerkiraan tiba dan persiapan trekking menuju kawah ratu (waktu tempuh 2 - 3 jam)\r\n\r\n- Curug ngumpet (14:30)\r\n\r\nSetelah selesai trekking kita akan menikmati curug ngumpet, curug ini bisa untuk berenang atau untuk main air. \r\n\r\n- Perjalanan menuju tempat oleh-oleh (16:30) \r\n\r\nTempat oleh-oleh ini banyak menjual makanan ringan yang sangat cocok untuk dijadikan oleh-oleh bagi orang-orang terdekat.\r\n\r\n- Perjalanan kembali menuju meeting point\r\n(16:00)\r\n\r\nMulai untuk perjalanan kembali dan sampai jumpa di perjalanan berikutnya.'),
(26, 'Sunrise Gunung Putri Lembang', 475000.00, 'Sunrise Gunung Putri Lembang adalah destinasi wisata alam di Lembang, Bandung, yang terkenal dengan pemandangan matahari terbit yang memukau. tempat ini menawarkan panorama pegunungan yang indah, dengan hamparan kabut tipis yang menyelimuti lembah di pagi hari. pengunjung dapat menikmati momen matahari terbit yang spektakuler, di mana sinar mentari perlahan menyinari dan menghangatkan pemandangan. Suasana yang tenang, udara sejuk khas pegunungan, dan keindahan alam yang menakjubkan.\r\n\r\nJalur pendakiannya relatif pendek dan dapat diakses dengan mudah, menjadikannya pilihan yang ideal untuk petualangan singkat sambil menikmati keindahan alam. setelah dari spot sunrise ini, kita akan mengunjungi lembah dewata yang instagrammable.', 'Paket tour termasuk :\r\n\r\n- Transport PP (Toll, Parkir, BBM) Hiace white horse\r\n\r\n-Tiket masuk gn. putri lembang\r\n\r\n-Tiket masuk lembah dewata\r\n\r\n- Tour leader\r\n\r\nPaket Tour tidak termasuk :\r\n\r\n- Makan\r\n- Penambahan atraksi wisata diluar program\r\n\r\n- Pengeluaran pribadi selama perjalanan\r\n\r\n* minimal keberangkatan 5 orang', '6720f670374d8-gunung_putri.jpg', '- Tiba di gn. putri lembang (05:00) \r\n\r\nKita akan trekking sekitar 15 menit menuju lokasi sunrise gn. putri lembang, setelah itu kita akan trekking benteng belanda. \r\n\r\n- Lembah dewata (09:00) \r\n\r\nSetibanya di lembah dewata, kalian dapat berfoto di lembah dewata yang banyak spot instagrammable.\r\n\r\n- Perjalanan menuju tempat oleh-oleh (12:30)\r\n\r\nTempat oleh-oleh ini banyak menjual makanan ringan yang sangat cocok untuk dijadikan oleh-oleh bagi orang-orang terdekat. \r\n\r\n- Perjalanan kembali menuju meeting point\r\n(15:00)\r\n\r\nMulai untuk perjalanan kembali dan sampai jumpa di perjalanan berikutnya.'),
(27, 'Kota Lama Bandung', 350000.00, 'Kota Lama Bandung adalah kawasan bersejarah di Kota Bandung yang menawarkan sekilas nostalgia ke masa kolonial Belanda. Di sini, pengunjung bisa melihat arsitektur bangunan tua yang khas dengan gaya art deco dan kolonial, yang masih terjaga hingga saat ini. Berlokasi di sekitar Alun-Alun Bandung dan Jalan Braga, Kota Lama Bandung dikenal sebagai pusat aktivitas budaya dan seni, dengan berbagai kafe, galeri seni, dan toko antik yang menambah pesona klasiknya. \r\n\r\nKawasan ini juga sering menjadi lokasi pameran dan acara budaya, menarik wisatawan yang ingin merasakan atmosfer Bandung tempo dulu. Dengan suasana yang unik dan bersejarah, Kota Lama Bandung menjadi destinasi favorit bagi penggemar sejarah, arsitektur, dan fotografi.', 'Paket tour termasuk :\r\n\r\n- Transport PP (Toll, Parkir, BBM) Hiace white horse\r\n\r\n- Tiket masuk gedung merdeka (museum konferensi asia afrika)\r\n\r\n- Tiket masuk gedung de majestic\r\n\r\n- Tour leader\r\n\r\nPaket Tour tidak termasuk :\r\n\r\n- Makan\r\n- Penambahan atraksi wisata diluar program\r\n\r\n- Pengeluaran pribadi selama perjalanan\r\n\r\nminimal keberangkatan 5 orang', '6720f77f42de2-kota_lama_bandung.jpg', '- Berkumpul di meeting point (07:00)\r\n\r\nBerkumpul di Jln. Terusan Gading Tutuka 1-B, Bandung (PT Jalan Dulu Asia)\r\n\r\n- Jalan Braga (09:00)\r\n\r\nBerjalan kaki menyusuri Jalan Braga, menikmati suasana klasik dengan bangunan art deco yang ikonik.\r\n\r\n- Gedung Merdeka (Museum Konferensi Asia Afrika) (12:30)\r\n\r\nMengunjungi Gedung Merdeka yang bersejarah, tempat berlangsungnya Konferensi Asia Afrika tahun 1955. Anda bisa melihat koleksi museum yang mencakup foto, dokumen, dan artefak penting. \r\n\r\n- Jalan Asia Afrika (14:00)\r\n\r\nMenyusuri Jalan Asia Afrika untuk melihat gedung-gedung kolonial lain, seperti Gedung De Majestic yang sering digunakan untuk acara seni dan budaya. Anda bisa berfoto dan menikmati arsitektur uniknya.\r\n\r\n- Alun-alun bandung\r\n(15:00)\r\n\r\nSetelah dari museum dan jalan asia afrika, anda akan dibawa untuk mengelilingi dan merasakan suasana alun-alun dari kota bandung.');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `paket`
--
ALTER TABLE `paket`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `paket`
--
ALTER TABLE `paket`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=38;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
